# Gitee Go 流水线配置
# 文档: https://gitee.com/help/articles/4295

name: gitee-go-pipeline

displayName: 'Sikuwa CI Pipeline'

triggers:
  push:
    - matchType: BRANCH
      branch: master
    - matchType: BRANCH
      branch: develop
  pull_request:
    - matchType: BRANCH
      branch: master

stages:
  - name: test
    displayName: '测试阶段'
    strategy: naturally
    trigger: auto
    executor:
      type: node-pool
      labels:
        - linux
    steps:
      - step: execute@python
        name: setup_python
        displayName: '设置 Python 环境'
        pythonVersion: '3.10'
        
      - step: execute@shell
        name: install_deps
        displayName: '安装依赖'
        script: |
          python -m pip install --upgrade pip
          pip install click tomli tomli-w nuitka pytest
          
      - step: execute@shell
        name: run_tests
        displayName: '运行测试'
        script: |
          pytest tests/ -v
