use std::collections::HashMap;
use std::fmt::Write;

use sikuwa_pir::module::{FuncDef, Module, Op, OpOperand, Terminator};
use sikuwa_pir::opcode::OpCode;
use sikuwa_pystat::FuncStat;
use sikuwa_pystat::PystatReport;

use crate::structs::emit_structs_h;

pub const SKW_ABI_STRING: &str = "1.0";

#[derive(Debug, Clone)]
pub struct CodegenOptions {
    pub module_guard: String,
    /// Emit `skw_module_t` descriptor in `.c`
    pub emit_module_desc: bool,
    /// Emit struct layouts for classes / closures in `.h`
    pub emit_structs: bool,
    /// Emit `{module}_pywrap.c` for CPython extension
    pub python_shim: bool,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            module_guard: String::new(),
            emit_module_desc: true,
            emit_structs: true,
            python_shim: false,
        }
    }
}

pub fn emit_module_h(pir: &Module, report: &PystatReport, opts: &CodegenOptions) -> String {
    let guard = if opts.module_guard.is_empty() {
        format!(
            "SIKUWA_{}_H",
            report.module.module.to_uppercase().replace('-', "_")
        )
    } else {
        opts.module_guard.clone()
    };
    let mut out = String::new();
    let _ = writeln!(out, "#ifndef {guard}");
    let _ = writeln!(out, "#define {guard}");
    let _ = writeln!(out, "#include \"sikuwa/abi.h\"");
    let _ = writeln!(out, "#include \"sikuwa/runtime.h\"");
    if opts.emit_module_desc {
        let _ = writeln!(out, "#include \"sikuwa/module.h\"");
    }
    let _ = writeln!(out);
    for f in &report.module.functions {
        if !f.static_eligible {
            continue;
        }
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| format!("{} {}", p.ty.c_type(), sanitize(&p.name)))
            .collect();
        let _ = writeln!(
            out,
            "SKW_API {} {}({});",
            f.return_ty.c_type(),
            skw_c_symbol(&f.symbol.0),
            params.join(", ")
        );
    }
    if opts.emit_module_desc {
        let _ = writeln!(
            out,
            "SKW_API extern const skw_module_t skw_module_{};",
            module_c_name(&report.module.module)
        );
    }
    if opts.emit_structs {
        emit_structs_h(pir, &mut out);
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "#endif /* {guard} */");
    out
}

pub fn emit_module_c(pir: &Module, report: &PystatReport, opts: &CodegenOptions) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "/* generated by sikuwa-codegen-c */");
    let _ = writeln!(out, "#define SKW_BUILDING_MODULE");
    for inc in &pir.c_includes {
        let _ = writeln!(out, "#include <{inc}>");
    }
    for ext in &pir.externs {
        if ext.library == "libc" {
            continue;
        }
        let _ = writeln!(out, "/* link: {} */", ext.library);
    }
    let _ = writeln!(out, "#include \"{}.h\"", pir.name);
    if opts.emit_module_desc {
        let _ = writeln!(out, "#include \"sikuwa/module.h\"");
    }
    let _ = writeln!(out);

    let stat_map: HashMap<_, _> = report
        .module
        .functions
        .iter()
        .map(|f| (f.symbol.0.clone(), f))
        .collect();

    let mut static_exports: Vec<(&FuncDef, &FuncStat)> = Vec::new();

    for func in &pir.functions {
        if let Some(stat) = stat_map.get(&func.symbol.0) {
            if stat.static_eligible {
                emit_func_c(func, stat, &mut out);
                static_exports.push((func, stat));
                let _ = writeln!(out);
            }
        }
    }

    if opts.emit_module_desc && !static_exports.is_empty() {
        emit_module_descriptor(pir, &static_exports, &mut out);
    }

    let _ = opts;
    out
}

fn emit_module_descriptor(
    pir: &Module,
    exports: &[(&FuncDef, &FuncStat)],
    out: &mut String,
) {
    let mod_name = module_c_name(&pir.name);
    let _ = writeln!(out, "static skw_fn_entry_t skw_{mod_name}_fns[] = {{");
    for (func, stat) in exports {
        let _ = writeln!(
            out,
            "    {{ \"{}\", SKW_SLOT_S0, (void *)({}) }},",
            func.symbol.0,
            skw_c_symbol(&func.symbol.0)
        );
        let _ = stat; // slot tier from stat in future
    }
    let _ = writeln!(out, "}};");
    let _ = writeln!(out);
    let hash = hex32(pir.source_hash);
    let _ = writeln!(
        out,
        "SKW_API const skw_module_t skw_module_{mod_name} = {{"
    );
    let _ = writeln!(out, "    .abi_major = SKW_ABI_VERSION_MAJOR,");
    let _ = writeln!(out, "    .abi_minor = SKW_ABI_VERSION_MINOR,");
    let _ = writeln!(out, "    .name = \"{}\",", pir.name);
    let _ = writeln!(out, "    .source_hash = {{ {hash} }},");
    let _ = writeln!(out, "    .fn_count = {},", exports.len());
    let _ = writeln!(out, "    .fns = skw_{mod_name}_fns,");
    let _ = writeln!(out, "}};");
}

fn emit_func_c(func: &FuncDef, stat: &FuncStat, out: &mut String) {
    let params: Vec<String> = stat
        .params
        .iter()
        .map(|p| format!("{} {}", p.ty.c_type(), sanitize(&p.name)))
        .collect();
    let _ = writeln!(
        out,
        "SKW_API {} {}({}) {{",
        stat.return_ty.c_type(),
        skw_c_symbol(&func.symbol.0),
        params.join(", ")
    );

    let mut env: HashMap<String, String> = HashMap::new();
    for p in &func.params {
        env.insert(p.clone(), sanitize(p));
    }

    let mut temps: HashMap<u32, String> = HashMap::new();
    let mut next_temp = 0u32;

    for block in &func.blocks {
        let _ = writeln!(out, "  {}:", block_label(&block.id));
        emit_block_body(block, out, &mut env, &mut temps, &mut next_temp);
        emit_terminator(block, out, &temps);
    }
    let _ = writeln!(out, "}}");
}

fn block_label(id: &sikuwa_pir::ids::BlockId) -> String {
    let safe = id.0.replace('-', "_");
    format!("skw_bb_{safe}")
}

fn emit_block_body(
    block: &sikuwa_pir::module::Block,
    out: &mut String,
    env: &mut HashMap<String, String>,
    temps: &mut HashMap<u32, String>,
    next_temp: &mut u32,
) {
    for op in &block.ops {
        if matches!(
            op.opcode,
            OpCode::LoadFast | OpCode::LoadCell | OpCode::Phi
        ) {
            if let Some(result) = op.result {
                if let Some(OpOperand::Name(n)) = op.operands.first() {
                    let src = env.get(n).cloned().unwrap_or_else(|| sanitize(n));
                    temps.insert(result.0, src);
                }
            }
        } else if !matches!(op.opcode, OpCode::StoreFast | OpCode::StoreCell) {
            if let Some(result) = op.result {
                let name = format!("t{}", next_temp);
                *next_temp += 1;
                let expr = emit_op_expr(op, env, temps);
                let _ = writeln!(out, "  {} {} = {};", c_type_for_op(op), name, expr);
                temps.insert(result.0, name);
            }
        } else if let OpCode::StoreFast = op.opcode {
            if let (Some(OpOperand::Name(n)), Some(OpOperand::Value(v))) =
                (op.operands.first(), op.operands.get(1))
            {
                if let Some(src) = temps.get(&v.0) {
                    env.insert(n.clone(), src.clone());
                }
            }
        }
    }
}

fn emit_terminator(
    block: &sikuwa_pir::module::Block,
    out: &mut String,
    temps: &HashMap<u32, String>,
) {
    match &block.term {
        Terminator::Branch { target } => {
            let _ = writeln!(out, "  goto {};", block_label(target));
        }
        Terminator::CondBranch {
            cond,
            then_block,
            else_block,
        } => {
            let c = temps.get(&cond.0).cloned().unwrap_or_else(|| "0".into());
            let _ = writeln!(out, "  if ({c}) goto {};", block_label(then_block));
            let _ = writeln!(out, "  goto {};", block_label(else_block));
        }
        Terminator::Return { value: Some(v) } => {
            let ret = temps.get(&v.0).cloned().unwrap_or_else(|| "0".into());
            let _ = writeln!(out, "  return {};", ret);
        }
        Terminator::Return { value: None } => {
            let _ = writeln!(out, "  return;");
        }
        Terminator::Unreachable => {
            let _ = writeln!(out, "  /* unreachable */");
        }
    }
}

fn emit_op_expr(op: &Op, env: &HashMap<String, String>, temps: &HashMap<u32, String>) -> String {
    let val = |i: usize| -> String {
        op.operands
            .get(i)
            .map(|o| operand_expr(o, env, temps))
            .unwrap_or_else(|| "0".into())
    };
    match op.opcode {
        OpCode::Const => val(0),
        OpCode::BinOpAdd => format!("{} + {}", val(0), val(1)),
        OpCode::BinOpSub => format!("{} - {}", val(0), val(1)),
        OpCode::BinOpMul => format!("{} * {}", val(0), val(1)),
        OpCode::BinOpTrueDiv => format!("(double){} / (double){}", val(0), val(1)),
        OpCode::BinOpFloorDiv => format!("{} / {}", val(0), val(1)),
        OpCode::BinOpMod => format!("{} % {}", val(0), val(1)),
        OpCode::UnaryNeg => format!("-{}", val(0)),
        OpCode::UnaryNot => format!("!{}", val(0)),
        OpCode::CompareLt => format!("{} < {}", val(0), val(1)),
        OpCode::CompareLe => format!("{} <= {}", val(0), val(1)),
        OpCode::CompareGt => format!("{} > {}", val(0), val(1)),
        OpCode::CompareGe => format!("{} >= {}", val(0), val(1)),
        OpCode::CompareEq => format!("{} == {}", val(0), val(1)),
        OpCode::CompareNe => format!("{} != {}", val(0), val(1)),
        OpCode::CallExtern => {
            if let Some(OpOperand::Name(name)) = op.operands.first() {
                let args: Vec<String> = (1..op.operands.len()).map(|i| val(i)).collect();
                format!("{}({})", name, args.join(", "))
            } else {
                "0".into()
            }
        }
        OpCode::Call => {
            let args: Vec<String> = (1..op.operands.len()).map(|i| val(i)).collect();
            match op.operands.first() {
                Some(OpOperand::Symbol(sym)) => {
                    format!("{}({})", skw_c_symbol(&sym.0), args.join(", "))
                }
                Some(OpOperand::Name(n)) => format!("{}({})", sanitize(n), args.join(", ")),
                _ => "0".into(),
            }
        }
        _ => "0".into(),
    }
}

fn operand_expr(
    op: &OpOperand,
    env: &HashMap<String, String>,
    temps: &HashMap<u32, String>,
) -> String {
    match op {
        OpOperand::Value(v) => temps.get(&v.0).cloned().unwrap_or_else(|| "0".into()),
        OpOperand::Name(n) => env.get(n).cloned().unwrap_or_else(|| sanitize(n)),
        OpOperand::Const(c) => const_to_c(c),
        _ => "0".into(),
    }
}

fn const_to_c(c: &sikuwa_pir::module::ConstValue) -> String {
    use sikuwa_pir::module::ConstValue;
    match c {
        ConstValue::Int(n) => n.to_string(),
        ConstValue::Bool(b) => {
            if *b {
                "1".into()
            } else {
                "0".into()
            }
        }
        ConstValue::Float(f) => f.to_string(),
        ConstValue::Str(s) => format!("\"{}\"", escape_c_str(s)),
        ConstValue::None => "0".into(),
    }
}

fn escape_c_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn c_type_for_op(op: &Op) -> &'static str {
    match op.opcode {
        OpCode::UnaryNot
        | OpCode::CompareLt
        | OpCode::CompareLe
        | OpCode::CompareGt
        | OpCode::CompareGe
        | OpCode::CompareEq
        | OpCode::CompareNe => "int64_t",
        OpCode::BinOpTrueDiv => "double",
        _ => "int64_t",
    }
}

/// PIR symbol → exported C symbol (`add.add` → `skw_add_add`).
pub fn skw_c_symbol(sym: &str) -> String {
    format!("skw_{}", sym.replace('.', "_").replace('@', ""))
}

pub fn module_c_name(name: &str) -> String {
    name.replace('-', "_").replace('.', "_")
}

fn sanitize(name: &str) -> String {
    if name == "type" {
        "typ".into()
    } else {
        name.replace('.', "_")
    }
}

fn hex32(bytes: [u8; 32]) -> String {
    bytes
        .iter()
        .map(|b| format!("0x{b:02x}"))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use sikuwa_pir::{lower_source, sample_add_module};
    use sikuwa_pystat::analyze_module;

    #[test]
    fn skw_symbol_prefix() {
        assert_eq!(skw_c_symbol("add.add"), "skw_add_add");
    }

    #[test]
    fn emit_add_c() {
        let pir = sample_add_module();
        let report = analyze_module(&pir);
        let opts = CodegenOptions {
            emit_module_desc: true,
            ..Default::default()
        };
        let c = emit_module_c(&pir, &report, &opts);
        assert!(c.contains("skw_sample_add"));
        assert!(c.contains("skw_module_sample"));
        assert!(c.contains("SKW_BUILDING_MODULE"));
    }

    #[test]
    fn emit_header_includes_abi() {
        let pir = lower_source("def add(a, b):\n    return a + b\n", "add.py").unwrap();
        let report = analyze_module(&pir);
        let h = emit_module_h(&pir, &report, &CodegenOptions::default());
        assert!(h.contains("sikuwa/abi.h"));
        assert!(h.contains("SKW_API"));
        assert!(h.contains("skw_add_add"));
    }

    #[test]
    fn emit_clamp_cfg() {
        let src = include_str!("../../../tests/fixtures/clamp.py");
        let pir = lower_source(src, "clamp.py").unwrap();
        let report = analyze_module(&pir);
        assert!(report.module.functions[0].static_eligible);
        let c = emit_module_c(&pir, &report, &CodegenOptions::default());
        assert!(c.contains("goto skw_bb_"));
        assert!(c.contains("skw_clamp_clamp"));
    }
}
